project:
  type: website
  preview:
    port: 4200

website:
  title: "Home"
  site-url: https://michaelaye.github.io
  twitter-card:
    creator: "@michaelaye"
  open-graph: true
  navbar:
    collapse: true
    left: 
#      - text: "Home"
#        file: index.qmd
      - text: "Blog"
        file: posts.qmd
      - talks.qmd
      - projects.qmd
      - bibliography.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/michaelaye/michaelaye.github.io
      - icon: mastodon
        href: https://mastodon.online/@michaelaye
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/michaelaye.bsky.social
execute:
  freeze: auto
format:
  html:
    theme:
      # Light (best readability): sandstone, cosmo, litera, flatly, lux, simplex
      light: sandstone
      # Dark (best inline code contrast): darkly, superhero, solar, cyborg
      dark: superhero
    css: styles.css
    toc: true
    lightbox: true
    highlight-style: atom-one
    link-external-icon: false
    link-external-newwindow: true




